//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Disney
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ticket.
    /// </summary>
    //  *** Start programmer edit section *** (Ticket CustomAttributes)

    //  *** End programmer edit section *** (Ticket CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("TicketE", new string[] {
            "Number as \'Number\'",
            "Person as \'Person\'",
            "Person.Name as \'Name\'"})]
    [View("TicketL", new string[] {
            "Number as \'Number\'",
            "Person.Name as \'Name\'"})]
    public class Ticket : ICSSoft.STORMNET.DataObject
    {
        
        private int fNumber;
        
        private IIS.Disney.Person fPerson;
        
        //  *** Start programmer edit section *** (Ticket CustomMembers)

        //  *** End programmer edit section *** (Ticket CustomMembers)

        
        /// <summary>
        /// Number.
        /// </summary>
        //  *** Start programmer edit section *** (Ticket.Number CustomAttributes)

        //  *** End programmer edit section *** (Ticket.Number CustomAttributes)
        public virtual int Number
        {
            get
            {
                //  *** Start programmer edit section *** (Ticket.Number Get start)

                //  *** End programmer edit section *** (Ticket.Number Get start)
                int result = this.fNumber;
                //  *** Start programmer edit section *** (Ticket.Number Get end)

                //  *** End programmer edit section *** (Ticket.Number Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Ticket.Number Set start)

                //  *** End programmer edit section *** (Ticket.Number Set start)
                this.fNumber = value;
                //  *** Start programmer edit section *** (Ticket.Number Set end)

                //  *** End programmer edit section *** (Ticket.Number Set end)
            }
        }
        
        /// <summary>
        /// Ticket.
        /// </summary>
        //  *** Start programmer edit section *** (Ticket.Person CustomAttributes)

        //  *** End programmer edit section *** (Ticket.Person CustomAttributes)
        [PropertyStorage(new string[] {
                "Person"})]
        public virtual IIS.Disney.Person Person
        {
            get
            {
                //  *** Start programmer edit section *** (Ticket.Person Get start)

                //  *** End programmer edit section *** (Ticket.Person Get start)
                IIS.Disney.Person result = this.fPerson;
                //  *** Start programmer edit section *** (Ticket.Person Get end)

                //  *** End programmer edit section *** (Ticket.Person Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Ticket.Person Set start)

                //  *** End programmer edit section *** (Ticket.Person Set start)
                this.fPerson = value;
                //  *** Start programmer edit section *** (Ticket.Person Set end)

                //  *** End programmer edit section *** (Ticket.Person Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TicketE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TicketE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TicketE", typeof(IIS.Disney.Ticket));
                }
            }
            
            /// <summary>
            /// "TicketL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TicketL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TicketL", typeof(IIS.Disney.Ticket));
                }
            }
        }
    }
}
